### ISSUE TITLE
Compile error after updating to VaporToOpenAPI 5.0.4 which pulls SwiftOpenAPI 3.0.9

### ISSUE THREAD

**Issue by finestructure** [dankinsoid/SwiftOpenAPI#5]
I'm getting

```
.../SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:2:8 No such module 'SwiftOpenAPIMacros'
```

when trying to compile locally (on macOS) and weirder errors for the same build in CI (on Linux):

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/6924719878

![CleanShot 2023-11-20 at 09 37 31@2x](https://github.com/dankinsoid/SwiftOpenAPI/assets/65520/8aead9ea-2406-422b-a8b1-9692ccf8ec79)

I'm going to try and figure out what's happening but I'm a bit at a loss at the moment 🤔

**Comment by dankinsoid** [comment]
@finestructure Yes, I'm a bit at a loss too, SwiftOpenAPI compiles fine and tests pass on my machine, but VaporToOpenAPI fails. There is no major changes actually, I just updated swift version to 5.9 and added a macro, so you can continue use 4.x.x now.

**Comment by finestructure** [comment]
Interesting - on the command line `swift test` _fails_ in SwiftOpenAPI but _works_ if I run the tests in Xcode.

```
~/D/SwiftOpenAPI on main took 5s                                                                                       •
❯ git rev-parse @
00122bcbce539dc2ce5a7c847cc53cfa3a282a23
~/D/SwiftOpenAPI on main                                                                                               •
❯ swift test
Building for debugging...
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  protocol descriptor for SwiftCompilerPlugin.CompilerPlugin, referenced from:
      l_got.$s19SwiftCompilerPlugin0bC0Mp in OpenAPIDescriptionMacro.swift.o
  static (extension in SwiftCompilerPlugin):SwiftCompilerPlugin.CompilerPlugin.main() throws -> (), referenced from:
      static SwiftOpenAPIMacros.OpenAPIDescriptionPlugin.$main() throws -> () in OpenAPIDescriptionMacro.swift.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[0/1] Linking SwiftOpenAPIPackageTests
error: fatalError
```

Looks like a problem with macros in command line builds?

**Comment by finestructure** [comment]
Not sure if this sheds some light or is just a red herring. When I add the macro target as a product:

```diff
	products: [
		.library(name: "SwiftOpenAPI", targets: ["SwiftOpenAPI"]),
+		.library(name: "SwiftOpenAPIMacros", targets: ["SwiftOpenAPIMacros"])
	],
```

tests keep passing fine in Xcode but `swift test` now shows a different error:

```
❯ swift test
warning: 'swiftopenapi': ignoring duplicate product 'SwiftOpenAPIMacros' (macro)
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/sas/Downloads/SwiftOpenAPI/Tests/SwiftOpenAPITests/SwiftOpenAPIMacrosTests.swift:25:8: error: external macro implementation type 'SwiftOpenAPIMacros.OpenAPIDescriptionMacro' could not be found for macro 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)'
struct Person: Codable {
       ^
/Users/sas/Downloads/SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:54:14: note: 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)' declared here
public macro OpenAPIAutoDescriptable(
             ^
/Users/sas/Downloads/SwiftOpenAPI/Tests/SwiftOpenAPITests/SwiftOpenAPIMacrosTests.swift:25:8: error: external macro implementation type 'SwiftOpenAPIMacros.OpenAPIDescriptionMacro' could not be found for macro 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)'
struct Person: Codable {
       ^
/Users/sas/Downloads/SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:54:14: note: 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)' declared here
public macro OpenAPIAutoDescriptable(
             ^
/Users/sas/Downloads/SwiftOpenAPI/Tests/SwiftOpenAPITests/SwiftOpenAPIMacrosTests.swift:25:8: error: external macro implementation type 'SwiftOpenAPIMacros.OpenAPIDescriptionMacro' could not be found for macro 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)'
struct Person: Codable {
       ^
/Users/sas/Downloads/SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:54:14: note: 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)' declared here
public macro OpenAPIAutoDescriptable(
             ^
/Users/sas/Downloads/SwiftOpenAPI/Tests/SwiftOpenAPITests/SwiftOpenAPIMacrosTests.swift:25:8: error: external macro implementation type 'SwiftOpenAPIMacros.OpenAPIDescriptionMacro' could not be found for macro 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)'
struct Person: Codable {
       ^
/Users/sas/Downloads/SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:54:14: note: 'OpenAPIAutoDescriptable(codingKeys:docCommentsOnly:includeAttributes:)' declared here
public macro OpenAPIAutoDescriptable(
             ^
/Users/sas/Downloads/SwiftOpenAPI/Tests/SwiftOpenAPITests/SwiftOpenAPIMacrosTests.swift:16:20: error: static property 'openAPIDescription' requires that 'Person' conform to 'OpenAPIDescriptable'
            Person.openAPIDescription?.asStringOpenAPIDescription,
                   ^
/Users/sas/Downloads/SwiftOpenAPI/Sources/SwiftOpenAPI/OpenAPIDescriptable.swift:9:8: note: where 'Self' = 'Person'
public extension OpenAPIDescriptable {
       ^
error: fatalError

error: fatalError
```

Not sure if this is helpful but I thought I'd share it just in case.

**Comment by dankinsoid** [comment]
@finestructure I fixed. The problem arose because I imported `import SwiftOpenAPIMacros` in SwiftOpenAPI

**Comment by finestructure** [comment]
Ah, that's great. Thank you!

**Comment by finestructure** [comment]
Unfortunately this is still failing when updating to VaporToOpenAPI 4.4.4 / SwiftOpenAPI 2.19.4:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/7081582318
